export enum State {
  NOT_ACCPTED_BY_COURIER = 'NOT_ACCPTED_BY_COURIER',
  ACCPTED_BY_COURIER = 'ACCPTED_BY_COURIER',
  RECIEVED_BY_COURIER = 'RECIEVED_BY_COURIER',
  TOWARD_DESTINATION = 'TOWARD_DESTINATION',
  DELIVERD = 'DELIVERD',
  CANCLED = 'CANCLED',
}
